import React,{useEffect,useMemo,useState} from 'react'
import { Plus, ChevronLeft, ChevronRight, MapPin, GripVertical, Play, Trash2, RotateCcw, Ban } from 'lucide-react'
import { listAppointments, listCustomers, listLeads, listProfiles, saveAppointment, saveLead, deleteAppointment, resetAppointmentWorkflow } from '../lib/api'
import { Badge, Empty, Field, Drawer, Tabs } from '../components/UI'
import PlaceAutocomplete from '../components/PlaceAutocomplete'
import { customerLabel, dateTime, leadLabel, localDateKey, mapsUrl, personLabel, timeOnly, wazeUrl } from '../lib/utils'
import { appointmentBlank, appointmentToForm, formToAppointment, monthCells, weekDays, slotTimes, slotIndex, eventHeight, rangeForView, serviceTypes, serviceDurations, isConsultationType } from '../lib/calendar'

const SLOT_HEIGHT=44
const statusTone=s=>s==='confirmed'?'success':s==='in_progress'?'warn':s==='cancelled'||s==='no-show'?'danger':'neutral'

export default function Appointments({prefill,onStartService,onStartConsultation}){
 const[view,setView]=useState(()=>window.innerWidth<820?'day':'month'),[cursor,setCursor]=useState(new Date()),[rows,setRows]=useState([]),[customers,setCustomers]=useState([]),[leads,setLeads]=useState([]),[profiles,setProfiles]=useState([])
 const[open,setOpen]=useState(false),[form,setForm]=useState(appointmentBlank()),[editing,setEditing]=useState(null),[selectedMap,setSelectedMap]=useState(null),[error,setError]=useState(''),[assignee,setAssignee]=useState('all'),[notice,setNotice]=useState(''),[statusBusy,setStatusBusy]=useState(false)
 const queryView=['agenda','map'].includes(view)?'month':view
 const load=async()=>{const[start,end]=rangeForView(queryView,cursor);const[a,c,l,p]=await Promise.all([listAppointments(start.toISOString(),end.toISOString()),listCustomers(),listLeads(),listProfiles()]);setRows(a);setCustomers(c);setLeads(l);setProfiles(p)}
 useEffect(()=>{load()},[cursor.getFullYear(),cursor.getMonth(),cursor.getDate(),queryView])
 useEffect(()=>{if(prefill?.record)openForPrefill(prefill)},[prefill?.kind,prefill?.record?.id,prefill?.service_type])
 const visibleRows=useMemo(()=>assignee==='all'?rows:rows.filter(x=>String(x.assigned_user_id||'')===assignee),[rows,assignee])
 const byDay=useMemo(()=>{const m={};visibleRows.forEach(x=>{const k=localDateKey(x.scheduled_at);(m[k] ||= []).push(x)});Object.values(m).forEach(v=>v.sort((a,b)=>new Date(a.scheduled_at)-new Date(b.scheduled_at)));return m},[visibleRows])
 const openNew=(date=new Date(),time='10:00')=>{const f=appointmentBlank(date);f.date=localDateKey(date);f.time=time;setForm(f);setEditing(null);setError('');setOpen(true)}
 function openForPrefill(p){const f=appointmentBlank();f.service_type=p.service_type||(p.kind==='lead'?'Studio Consultation':p.record?.lifecycle_stage==='signed'?'New System Installation':'Maintenance');f.duration_min=serviceDurations[f.service_type]||60;if(p.kind==='lead'){f.lead_id=p.record.id;f.customer_id='';if(f.service_type==='Free Home Consultation'){f.location_type='home';f.travel_buffer_before=30;f.travel_buffer_after=30}}else{f.customer_id=p.record.id;f.lead_id='';Object.assign(f,{address:p.record.address||'',place_name:p.record.place_name||'',google_place_id:p.record.google_place_id||'',lat:p.record.lat||null,lng:p.record.lng||null,google_maps_url:p.record.google_maps_url||''})}setForm(f);setEditing(null);setError('');setOpen(true)}
 const selectCustomer=id=>{const c=customers.find(x=>x.id===id);setForm({...form,customer_id:id,lead_id:'',address:c?.address||'',place_name:c?.place_name||'',google_place_id:c?.google_place_id||'',lat:c?.lat||null,lng:c?.lng||null,google_maps_url:c?.google_maps_url||''})}
 const selectConsultPerson=value=>{const[kind,id]=value.split(':');if(kind==='lead'){setForm({...form,lead_id:id,customer_id:'',address:'',place_name:'',google_place_id:'',lat:null,lng:null,google_maps_url:''})}else{const c=customers.find(x=>x.id===id);setForm({...form,customer_id:id,lead_id:'',address:c?.address||'',place_name:c?.place_name||'',google_place_id:c?.google_place_id||'',lat:c?.lat||null,lng:c?.lng||null,google_maps_url:c?.google_maps_url||''})}}
 const submit=async e=>{e.preventDefault();setError('');try{if(isConsultationType(form.service_type)&&!form.lead_id&&!form.customer_id)throw new Error('Select a lead or existing client for this consultation.');if(!isConsultationType(form.service_type)&&!form.customer_id)throw new Error('Technical service bookings require a signed client.');const payload=formToAppointment(form);await saveAppointment(payload,editing);if(form.lead_id&&isConsultationType(form.service_type)){const l=leads.find(x=>x.id===form.lead_id);if(l&&!['signed','lost'].includes(l.stage))await saveLead({stage:'consultation_booked',follow_up_date:null},form.lead_id)}setOpen(false);setEditing(null);setNotice(editing?'Booking updated':'Booking created');setTimeout(()=>setNotice(''),2200);await load()}catch(e){setError(e.message.includes('appointment_no_overlap')?'This time overlaps another booking for the same person. Choose another time or assignee.':e.message)}}
 const edit=x=>{setEditing(x.id);setForm(appointmentToForm(x));setError('');setOpen(true)}
 const move=async(a,date,time=null)=>{try{const d=new Date(a.scheduled_at);const newLocal=new Date(date);if(time){const[hh,mm]=time.split(':').map(Number);newLocal.setHours(hh,mm,0,0)}else newLocal.setHours(d.getHours(),d.getMinutes(),0,0);await saveAppointment({scheduled_at:newLocal.toISOString()},a.id);setNotice(`Moved to ${dateTime(newLocal)}`);setTimeout(()=>setNotice(''),2200);await load()}catch(e){alert(e.message.includes('appointment_no_overlap')?'That move conflicts with another booking for the same person.':e.message)}}
 const changeService=v=>{const home=v==='Free Home Consultation';const studioConsult=v==='Studio Consultation';setForm({...form,service_type:v,duration_min:serviceDurations[v]||60,customer_id:form.customer_id,lead_id:isConsultationType(v)?form.lead_id:'',location_type:home?'home':studioConsult?'studio':form.location_type,travel_buffer_before:home?30:studioConsult?0:form.travel_buffer_before,travel_buffer_after:home?30:studioConsult?0:form.travel_buffer_after})}
 const nav=dir=>{const d=new Date(cursor);if(view==='month'||view==='agenda'||view==='map')d.setMonth(d.getMonth()+dir);else if(view==='week')d.setDate(d.getDate()+7*dir);else d.setDate(d.getDate()+dir);setCursor(d)}
 const label=view==='month'||view==='agenda'||view==='map'?cursor.toLocaleDateString('en-MY',{month:'long',year:'numeric'}):view==='week'?`${weekDays(cursor)[0].toLocaleDateString('en-MY',{day:'numeric',month:'short'})} – ${weekDays(cursor)[6].toLocaleDateString('en-MY',{day:'numeric',month:'short',year:'numeric'})}`:cursor.toLocaleDateString('en-MY',{weekday:'long',day:'numeric',month:'long',year:'numeric'})
 const home=visibleRows.filter(x=>x.location_type==='home'&&!['cancelled','no-show'].includes(x.status)&&new Date(x.scheduled_at)>new Date(Date.now()-86400000)).sort((a,b)=>new Date(a.scheduled_at)-new Date(b.scheduled_at))
 const consultPersonValue=form.lead_id?`lead:${form.lead_id}`:form.customer_id?`customer:${form.customer_id}`:''
 const currentRow=editing?rows.find(x=>x.id===editing):null
 const action=()=>{const a={...currentRow,...form,id:editing,scheduled_at:formToAppointment(form).scheduled_at,customers:currentRow?.customers,leads:currentRow?.leads};setOpen(false);isConsultationType(form.service_type)?onStartConsultation?.(a):onStartService?.(a)}
 const resetActive=async target=>{if(!editing)return;const label=target==='confirmed'?'return this job to Booked':'cancel this in-progress job';if(!confirm(`Are you sure you want to ${label}?`))return;setStatusBusy(true);setError('');try{await resetAppointmentWorkflow(editing,target);setOpen(false);setEditing(null);setNotice(target==='confirmed'?'Returned to booked':'Booking cancelled');setTimeout(()=>setNotice(''),2200);await load()}catch(e){setError(e.message||'Could not change status.')}finally{setStatusBusy(false)}}

 const removeBooking=async()=>{if(!editing)return;if(['in_progress','completed'].includes(form.status)){setError('Started or completed bookings cannot be deleted here. Delete the test client/history instead.');return}if(!confirm('Delete this booking? This is intended for test or incorrect bookings.'))return;try{await deleteAppointment(editing);setOpen(false);setEditing(null);setNotice('Booking deleted');setTimeout(()=>setNotice(''),2200);await load()}catch(e){setError(e.message)}}
 return <div className="page calendar-page">
  <div className="page-head"><div><span className="eyebrow">SCHEDULE</span><h1>Calendar</h1><p>Consultations and technical services share one calendar, but use different workflows.</p></div><button className="btn btn-primary" onClick={()=>openNew(new Date(),'10:00')}><Plus size={18}/>New booking</button></div>
  {notice&&<div className="toast-inline">{notice}</div>}
  <div className="calendar-commandbar"><Tabs value={view} onChange={setView} items={[{value:'month',label:'Month'},{value:'week',label:'Week'},{value:'day',label:'Day'},{value:'agenda',label:'Agenda'},{value:'map',label:'Map'}]}/><div className="calendar-nav"><button className="icon-btn" onClick={()=>nav(-1)}><ChevronLeft size={19}/></button><button className="btn btn-ghost btn-sm" onClick={()=>setCursor(new Date())}>Today</button><strong>{label}</strong><button className="icon-btn" onClick={()=>nav(1)}><ChevronRight size={19}/></button></div><div className="calendar-filters"><input aria-label="Jump to date" className="date-jump" type="date" value={localDateKey(cursor)} onChange={e=>e.target.value&&setCursor(new Date(`${e.target.value}T12:00:00`))}/><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="all">All team</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></div></div>
  {view==='month'&&<MonthView cursor={cursor} rowsByDay={byDay} onNew={openNew} onEdit={edit} onMove={move}/>} {view==='week'&&<TimeGrid days={weekDays(cursor)} rowsByDay={byDay} onNew={openNew} onEdit={edit} onMove={move}/>} {view==='day'&&<TimeGrid days={[cursor]} rowsByDay={byDay} onNew={openNew} onEdit={edit} onMove={move}/>} {view==='agenda'&&<Agenda rowsByDay={byDay} onEdit={edit}/>} {view==='map'&&<MapView home={home} selected={selectedMap} setSelected={setSelectedMap}/>} 
  <Drawer open={open} onClose={()=>setOpen(false)} title={editing?'Booking details':'New booking'} eyebrow="BOOKING"><form className="form-grid booking-form" onSubmit={submit}>
   {error&&<div className="notice danger span-2">{error}</div>}
   <Field label="Booking type"><select value={form.service_type} onChange={e=>changeService(e.target.value)}>{serviceTypes.map(x=><option key={x}>{x}</option>)}</select></Field>
   {isConsultationType(form.service_type)?<Field label="Lead / existing client"><select required value={consultPersonValue} onChange={e=>selectConsultPerson(e.target.value)}><option value="">Select prospect</option><optgroup label="Leads">{leads.filter(l=>l.id===form.lead_id||!['signed','lost'].includes(l.stage)).map(l=><option value={`lead:${l.id}`} key={l.id}>{leadLabel(l)}{l.phone?` · ${l.phone}`:''}</option>)}</optgroup><optgroup label="Existing clients">{customers.map(c=><option value={`customer:${c.id}`} key={c.id}>{customerLabel(c)}</option>)}</optgroup></select></Field>:<Field label="Signed client"><select required value={form.customer_id} onChange={e=>selectCustomer(e.target.value)}><option value="">Select client</option>{customers.map(c=><option value={c.id} key={c.id}>{customerLabel(c)}{c.lifecycle_stage?` · ${c.lifecycle_stage}`:''}</option>)}</select></Field>}
   <Field label="Date"><input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></Field><Field label="Start time"><input required type="time" step="900" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></Field>
   <Field label="Duration"><div className="duration-row"><input type="number" min="15" step="15" value={form.duration_min} onChange={e=>setForm({...form,duration_min:e.target.value})}/><span>minutes</span></div></Field><Field label="Assigned to"><select value={form.assigned_user_id} onChange={e=>setForm({...form,assigned_user_id:e.target.value})}><option value="">Unassigned</option>{profiles.map(p=><option value={p.id} key={p.id}>{p.full_name}</option>)}</select></Field>
   <Field label="Status">{form.status==='in_progress'?<div className="status-workflow-card"><div><Badge tone="warn">in progress</Badge><span>The {isConsultationType(form.service_type)?'consultation':'service'} has started. You can continue it, return it to Booked if started by mistake, or cancel it.</span></div><div className="status-workflow-actions"><button type="button" className="btn btn-ghost btn-sm" disabled={statusBusy} onClick={()=>resetActive('confirmed')}><RotateCcw size={14}/>Return to booked</button><button type="button" className="btn btn-danger-ghost btn-sm" disabled={statusBusy} onClick={()=>resetActive('cancelled')}><Ban size={14}/>Cancel</button></div></div>:form.status==='completed'?<div className="status-readonly"><Badge tone="success">completed</Badge><span>Completed work is locked because it may already have sales, stock or payment records.</span></div>:<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['tentative','confirmed','cancelled','no-show'].map(x=><option key={x}>{x.replace('_',' ')}</option>)}</select>}</Field><Field label="Location"><select value={form.location_type} onChange={e=>setForm({...form,location_type:e.target.value})}><option value="studio">Studio</option><option value="home">Home visit</option></select></Field>
   {form.location_type==='home'&&<><Field label="Travel buffer"><div className="dual-input"><input title="Before" type="number" min="0" step="15" value={form.travel_buffer_before} onChange={e=>setForm({...form,travel_buffer_before:e.target.value})}/><input title="After" type="number" min="0" step="15" value={form.travel_buffer_after} onChange={e=>setForm({...form,travel_buffer_after:e.target.value})}/></div></Field><div className="span-2"><PlaceAutocomplete value={{place_name:form.place_name,formatted_address:form.address,google_place_id:form.google_place_id,lat:form.lat,lng:form.lng,google_maps_url:form.google_maps_url}} onChange={p=>setForm({...form,address:p.formatted_address,place_name:p.place_name,google_place_id:p.google_place_id,lat:p.lat,lng:p.lng,google_maps_url:p.google_maps_url})}/></div><Field label="Address"><textarea value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></Field></>}
   <Field label="Notes"><textarea value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></Field>
   <div className="form-actions booking-actions">{editing&&!['in_progress','completed'].includes(form.status)&&<button type="button" className="btn btn-danger-ghost" onClick={removeBooking}><Trash2 size={16}/>Delete</button>}{editing&&['tentative','confirmed','in_progress'].includes(form.status)&&<button type="button" className="btn btn-service" onClick={action}><Play size={16}/>{form.status==='in_progress'?'Continue ': 'Start '}{isConsultationType(form.service_type)?'consultation':'service'}</button>}<span className="grow"/><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary">Save booking</button></div>
  </form></Drawer>
 </div>
}

function MonthView({cursor,rowsByDay,onNew,onEdit,onMove}){const cells=monthCells(cursor);return <section className="panel calendar-panel month-calendar"><div className="week-head">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=><span key={x}>{x}</span>)}</div><div className="month-grid">{cells.map((d,i)=>{const key=localDateKey(d),items=rowsByDay[key]||[],outside=d.getMonth()!==cursor.getMonth(),today=key===localDateKey(new Date());return <div className={`day-cell ${outside?'outside':''} ${today?'today':''}`} key={i} onDoubleClick={()=>onNew(d,'10:00')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/appointment-id');const a=Object.values(rowsByDay).flat().find(x=>x.id===id);if(a)onMove(a,d)}}><button className="day-add" onClick={()=>onNew(d,'10:00')}><span className="day-num">{d.getDate()}</span><Plus size={14}/></button><div className="day-events">{items.slice(0,4).map(a=><button draggable onDragStart={e=>{e.stopPropagation();e.dataTransfer.setData('text/appointment-id',a.id)}} className={`month-event status-${a.status} ${isConsultationType(a.service_type)?'consultation-event':''}`} key={a.id} onClick={e=>{e.stopPropagation();onEdit(a)}}><GripVertical size={11}/><span>{timeOnly(a.scheduled_at)}</span><strong>{personLabel(a)}</strong></button>)}{items.length>4&&<small>+{items.length-4} more</small>}</div></div>})}</div></section>}
function TimeGrid({days,rowsByDay,onNew,onEdit,onMove}){const slots=slotTimes();return <section className="panel timegrid-panel"><div className={`timegrid ${days.length===1?'day-mode':'week-mode'}`}><div className="timegrid-head"><div/>{days.map(d=><div key={localDateKey(d)} className={localDateKey(d)===localDateKey(new Date())?'today':''}><span>{d.toLocaleDateString('en-MY',{weekday:'short'})}</span><strong>{d.getDate()}</strong></div>)}</div><div className="timegrid-scroll"><div className="timegrid-body" style={{'--day-count':days.length}}><div className="time-axis">{slots.map((t,i)=><div key={t} style={{height:SLOT_HEIGHT}}>{i%2===0?t:''}</div>)}</div>{days.map(d=>{const key=localDateKey(d),items=(rowsByDay[key]||[]).filter(a=>{const h=new Date(a.scheduled_at).getHours();return h>=8&&h<22});return <div className="time-day" key={key} style={{height:slots.length*SLOT_HEIGHT}}>{slots.map((t,i)=><button key={t} className="time-slot" style={{top:i*SLOT_HEIGHT,height:SLOT_HEIGHT}} onClick={()=>onNew(d,t)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/appointment-id');const a=Object.values(rowsByDay).flat().find(x=>x.id===id);if(a)onMove(a,d,t)}}/>)}{items.map(a=>{const top=slotIndex(a.scheduled_at)*SLOT_HEIGHT,height=Math.max(34,eventHeight(a.duration_min)*SLOT_HEIGHT-3);return <button draggable key={a.id} className={`time-event status-${a.status} ${isConsultationType(a.service_type)?'consultation-event':''}`} style={{top,height}} onDragStart={e=>e.dataTransfer.setData('text/appointment-id',a.id)} onClick={()=>onEdit(a)}><span>{timeOnly(a.scheduled_at)}</span><strong>{personLabel(a)}</strong><small>{a.service_type}</small></button>})}</div>})}</div></div></div></section>}
function Agenda({rowsByDay,onEdit}){const entries=Object.entries(rowsByDay).sort(([a],[b])=>a.localeCompare(b));return <section className="panel">{entries.length?<div className="agenda-list">{entries.map(([day,arr])=><div className="agenda-day" key={day}><div className="agenda-date"><strong>{new Date(day+'T12:00:00').toLocaleDateString('en-MY',{weekday:'short',day:'2-digit'})}</strong><span>{new Date(day+'T12:00:00').toLocaleDateString('en-MY',{month:'short'})}</span></div><div className="agenda-items">{arr.map(a=><button key={a.id} onClick={()=>onEdit(a)}><span className="agenda-time">{timeOnly(a.scheduled_at)}</span><div className="grow"><strong>{personLabel(a)}</strong><span>{a.service_type} · {a.profiles?.full_name||'Unassigned'} · {a.location_type==='home'?'Home':'Studio'}</span></div><Badge tone={statusTone(a.status)}>{a.status.replace('_',' ')}</Badge></button>)}</div></div>)}</div>:<Empty title="No appointments in this period"/>}</section>}
function MapView({home,selected,setSelected}){const a=selected||home[0];return <div className="map-layout"><section className="panel home-visit-list"><div className="section-head"><div><span className="eyebrow">HOME VISITS</span><h2>Upcoming locations</h2></div></div>{home.length?home.map(x=><button className={a?.id===x.id?'active':''} key={x.id} onClick={()=>setSelected(x)}><MapPin size={18}/><div className="grow"><strong>{personLabel(x)}</strong><span>{dateTime(x.scheduled_at)} · {x.place_name||x.address||'No address'}</span></div><ChevronRight size={17}/></button>):<Empty title="No home visits"/>}</section><section className="panel map-card">{a?(()=>{const q=a.lat&&a.lng?`${a.lat},${a.lng}`:a.address;return <><div className="map-frame"><iframe title="map" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={`https://www.google.com/maps?q=${encodeURIComponent(q||'Johor Bahru')}&z=15&output=embed`}/></div><div className="map-info"><div><strong>{personLabel(a)}</strong><span>{a.place_name||a.address}</span></div><div className="inline-actions"><a className="btn btn-ghost btn-sm" target="_blank" rel="noreferrer" href={mapsUrl(a)}>Google Maps</a><a className="btn btn-primary btn-sm" target="_blank" rel="noreferrer" href={wazeUrl(a)}>Waze</a></div></div></>})():<Empty title="Choose a home visit"/>}</section></div>}
