import React,{useEffect,useMemo,useState} from 'react'
import { Plus, Search, ChevronRight, MapPin, AtSign } from 'lucide-react'
import { listCustomers, saveCustomer } from '../lib/api'
import { Empty, Field, Modal } from '../components/UI'
import PlaceAutocomplete from '../components/PlaceAutocomplete'
import { customerLabel, initials, shortDate } from '../lib/utils'

const blank={name:'',whatsapp_name:'',phone:'',email:'',area:'',address:'',place_name:'',google_place_id:'',lat:null,lng:null,google_maps_url:'',notes:'',status:'active'}
export default function Customers({onOpen}){
 const [rows,setRows]=useState([]),[q,setQ]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState(blank),[busy,setBusy]=useState(false)
 const load=()=>listCustomers().then(setRows); useEffect(()=>{load()},[])
 const filtered=useMemo(()=>rows.filter(x=>`${x.name||''} ${x.whatsapp_name||''} ${x.phone||''} ${x.area||''} ${x.address||''}`.toLowerCase().includes(q.toLowerCase())),[rows,q])
 const placeValue={place_name:form.place_name,formatted_address:form.address,google_place_id:form.google_place_id,lat:form.lat,lng:form.lng,google_maps_url:form.google_maps_url}
 const submit=async e=>{e.preventDefault();if(!form.name.trim()&&!form.whatsapp_name.trim()&&!form.phone.trim()){alert('Add at least a name, WhatsApp display name, or phone number.');return}setBusy(true);try{const c=await saveCustomer({...form,name:form.name.trim()||null,whatsapp_name:form.whatsapp_name.trim()||null,phone:form.phone.trim()||null,lat:form.lat||null,lng:form.lng||null});setOpen(false);setForm(blank);await load();onOpen?.(c.id)}finally{setBusy(false)}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow">CUSTOMERS</span><h1>Customers</h1><p>Everything about a customer in one clean profile.</p></div><button className="btn btn-primary" onClick={()=>{setForm(blank);setOpen(true)}}><Plus size={18}/>New customer</button></div>
 <div className="toolbar"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, WhatsApp, phone, area..."/></div><span className="toolbar-count">{filtered.length} customers</span></div>
 <section className="panel customer-grid-panel">{filtered.length?<div className="customer-grid">{filtered.map(x=><button className="customer-card" key={x.id} onClick={()=>onOpen?.(x.id)}><div className="customer-card-top"><div className="avatar large">{initials(x)}</div><div className="grow"><strong>{customerLabel(x)}</strong><span>{x.name&&x.whatsapp_name?`${x.name} · @${x.whatsapp_name}`:(x.phone||x.area||'Profile ready')}</span></div><ChevronRight size={18}/></div><div className="customer-card-meta"><span><MapPin size={15}/>{x.place_name||x.area||x.address||'No location saved'}</span><span>Since {shortDate(x.created_at)}</span></div></button>)}</div>:<Empty title="No customers yet" text="Convert a lead or add a customer manually."/>}</section>
 <Modal open={open} onClose={()=>setOpen(false)} title="New customer" wide><form className="form-grid" onSubmit={submit}><Field label="Name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Real name if known"/></Field><Field label="WhatsApp / display name"><div className="input-icon"><AtSign size={17}/><input value={form.whatsapp_name} onChange={e=>setForm({...form,whatsapp_name:e.target.value})}/></div></Field><Field label="Phone / WhatsApp"><input inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Email"><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Area"><input value={form.area} onChange={e=>setForm({...form,area:e.target.value})}/></Field><div className="span-2"><PlaceAutocomplete value={placeValue} onChange={p=>setForm({...form,address:p.formatted_address,place_name:p.place_name,google_place_id:p.google_place_id,lat:p.lat,lng:p.lng,google_maps_url:p.google_maps_url})}/></div><Field label="Full address (manual / backup)"><textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></Field><Field label="Notes"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><div className="form-actions"><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={busy}>{busy?'Saving...':'Create customer'}</button></div></form></Modal>
 </div>
}
