import React,{useEffect,useMemo,useState} from 'react'
import { Plus, Search, Package, Droplets, ArrowUpDown } from 'lucide-react'
import { listHairSystems, saveHairSystem, listConsumables, saveConsumable, adjustConsumable, listCustomers, installHairSystem } from '../lib/api'
import { Badge, Empty, Field, Modal, Tabs } from '../components/UI'
import { customerLabel, localDateKey, money, shortDate } from '../lib/utils'
import { canDirectInstallHairSystem } from '../lib/guards'

const hsBlank={sku:'',base:'',colour:'1B',size:'',density:'100%',length:'6 inch',hair_type:'Human Hair',supplier:'',batch:'',cost:'',selling_price:'',status:'available',received_date:localDateKey(new Date())}
const conBlank={name:'',sku:'',category:'Tape',unit:'roll',qty:'',min_qty:'',supplier:'',unit_cost:''}
export default function Inventory(){
 const [tab,setTab]=useState('systems'),[systems,setSystems]=useState([]),[cons,setCons]=useState([]),[customers,setCustomers]=useState([]),[q,setQ]=useState(''),[hsOpen,setHsOpen]=useState(false),[conOpen,setConOpen]=useState(false),[adjust,setAdjust]=useState(null),[install,setInstall]=useState(null),[hsForm,setHsForm]=useState(hsBlank),[conForm,setConForm]=useState(conBlank),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=async()=>{try{const [h,c,cu]=await Promise.all([listHairSystems(),listConsumables(),listCustomers()]);setSystems(h);setCons(c);setCustomers(cu)}catch(e){setError(e.message||'Could not load inventory.')}};useEffect(()=>{load()},[])
 const saveSystem=async e=>{e.preventDefault();setBusy(true);setError('');try{await saveHairSystem({...hsForm,cost:Number(hsForm.cost||0),selling_price:Number(hsForm.selling_price||0),received_date:hsForm.received_date||null});setHsOpen(false);setHsForm(hsBlank);await load()}catch(e){setError(e.message||'Could not save hair system.')}finally{setBusy(false)}}
 const submitConsumable=async e=>{e.preventDefault();setBusy(true);setError('');try{await saveConsumable({...conForm,qty:Number(conForm.qty||0),min_qty:Number(conForm.min_qty||0),unit_cost:Number(conForm.unit_cost||0)});setConOpen(false);setConForm(conBlank);await load()}catch(e){setError(e.message||'Could not save consumable.')}finally{setBusy(false)}}
 const fs=useMemo(()=>systems.filter(x=>`${x.code} ${x.sku} ${x.base} ${x.colour} ${x.status}`.toLowerCase().includes(q.toLowerCase())),[systems,q]);const fc=useMemo(()=>cons.filter(x=>`${x.name} ${x.sku} ${x.category}`.toLowerCase().includes(q.toLowerCase())),[cons,q])
 return <div className="page"><div className="page-head"><div><span className="eyebrow">STOCK</span><h1>Inventory</h1><p>Simple stock control: available, reserved, installed and low-stock consumables.</p></div><button className="btn btn-primary" onClick={()=>tab==='systems'?setHsOpen(true):setConOpen(true)}><Plus size={17}/>Add {tab==='systems'?'hair system':'consumable'}</button></div>
 {error&&<div className="notice danger">{error}</div>}
 <div className="inventory-top"><Tabs value={tab} onChange={setTab} items={[{value:'systems',label:'Hair Systems'},{value:'consumables',label:'Consumables'}]}/><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search inventory..."/></div></div>
 {tab==='systems'&&<section className="panel table-panel">{fs.length?<div className="responsive-table"><table><thead><tr><th>System</th><th>Specs</th><th>Status</th><th>Customer</th><th>Cost / Sell</th><th></th></tr></thead><tbody>{fs.map(x=><tr key={x.id}><td data-label="System"><strong>{x.code}</strong><span>{x.sku||'No SKU'} · {x.supplier||'No supplier'}</span></td><td data-label="Specs">{[x.base,x.colour,x.size,x.density,x.length].filter(Boolean).join(' · ')}</td><td data-label="Status"><Badge tone={x.status==='available'?'success':x.status==='installed'?'neutral':x.status==='reserved'?'warn':'danger'}>{x.status}</Badge></td><td data-label="Customer">{x.customers?customerLabel(x.customers):'—'}</td><td data-label="Cost / Sell"><strong>{money(x.cost)}</strong><span>{money(x.selling_price)}</span></td><td className="row-actions">{canDirectInstallHairSystem(x)&&<button className="btn btn-ghost btn-sm" onClick={()=>{setError('');setInstall(x)}}>Assign / Install</button>}</td></tr>)}</tbody></table></div>:<Empty title="No hair systems" text="Stock in each physical unit with its own unique code."/>}</section>}
 {tab==='consumables'&&<section className="panel table-panel">{fc.length?<div className="responsive-table"><table><thead><tr><th>Consumable</th><th>Category</th><th>On hand</th><th>Minimum</th><th>Supplier</th><th></th></tr></thead><tbody>{fc.map(x=>{const low=Number(x.qty)<=Number(x.min_qty);return <tr key={x.id}><td data-label="Consumable"><strong>{x.name}</strong><span>{x.sku||'No SKU'}</span></td><td data-label="Category">{x.category}</td><td data-label="On hand"><strong className={low?'text-danger':''}>{x.qty} {x.unit}</strong>{low&&<Badge tone="danger">Low</Badge>}</td><td data-label="Minimum">{x.min_qty} {x.unit}</td><td data-label="Supplier">{x.supplier||'—'}</td><td className="row-actions"><button className="btn btn-ghost btn-sm" onClick={()=>{setError('');setAdjust(x)}}><ArrowUpDown size={15}/>Adjust</button></td></tr>})}</tbody></table></div>:<Empty title="No consumables" text="Add tapes, glue, remover, shampoo and other service stock."/>}</section>}
 <Modal open={hsOpen} onClose={()=>setHsOpen(false)} title="Stock in hair system" wide><form className="form-grid" onSubmit={saveSystem}>{error&&<div className="notice danger span-2">{error}</div>}<Field label="SKU"><input value={hsForm.sku} onChange={e=>setHsForm({...hsForm,sku:e.target.value})}/></Field><Field label="Base"><input value={hsForm.base} onChange={e=>setHsForm({...hsForm,base:e.target.value})} placeholder="0.06 Poly / Lace..."/></Field><Field label="Colour"><input value={hsForm.colour} onChange={e=>setHsForm({...hsForm,colour:e.target.value})}/></Field><Field label="Size"><input value={hsForm.size} onChange={e=>setHsForm({...hsForm,size:e.target.value})}/></Field><Field label="Density"><input value={hsForm.density} onChange={e=>setHsForm({...hsForm,density:e.target.value})}/></Field><Field label="Length"><input value={hsForm.length} onChange={e=>setHsForm({...hsForm,length:e.target.value})}/></Field><Field label="Hair type"><input value={hsForm.hair_type} onChange={e=>setHsForm({...hsForm,hair_type:e.target.value})}/></Field><Field label="Supplier"><input value={hsForm.supplier} onChange={e=>setHsForm({...hsForm,supplier:e.target.value})}/></Field><Field label="Batch"><input value={hsForm.batch} onChange={e=>setHsForm({...hsForm,batch:e.target.value})}/></Field><Field label="Received date"><input type="date" value={hsForm.received_date} onChange={e=>setHsForm({...hsForm,received_date:e.target.value})}/></Field><Field label="Cost (RM)"><input type="number" step="0.01" value={hsForm.cost} onChange={e=>setHsForm({...hsForm,cost:e.target.value})}/></Field><Field label="Selling price (RM)"><input type="number" step="0.01" value={hsForm.selling_price} onChange={e=>setHsForm({...hsForm,selling_price:e.target.value})}/></Field><div className="form-actions"><button disabled={busy} className="btn btn-primary">{busy?'Saving...':'Stock in'}</button></div></form></Modal>
 <Modal open={conOpen} onClose={()=>setConOpen(false)} title="Add consumable"><form className="form-grid" onSubmit={submitConsumable}>{error&&<div className="notice danger span-2">{error}</div>}<Field label="Name"><input required value={conForm.name} onChange={e=>setConForm({...conForm,name:e.target.value})}/></Field><Field label="SKU"><input value={conForm.sku} onChange={e=>setConForm({...conForm,sku:e.target.value})}/></Field><Field label="Category"><select value={conForm.category} onChange={e=>setConForm({...conForm,category:e.target.value})}>{['Tape','Adhesive','Remover','Cleaning','Styling','Other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Unit"><input value={conForm.unit} onChange={e=>setConForm({...conForm,unit:e.target.value})}/></Field><Field label="Opening qty"><input type="number" step="0.01" value={conForm.qty} onChange={e=>setConForm({...conForm,qty:e.target.value})}/></Field><Field label="Low-stock level"><input type="number" step="0.01" value={conForm.min_qty} onChange={e=>setConForm({...conForm,min_qty:e.target.value})}/></Field><Field label="Supplier"><input value={conForm.supplier} onChange={e=>setConForm({...conForm,supplier:e.target.value})}/></Field><Field label="Unit cost (RM)"><input type="number" step="0.01" value={conForm.unit_cost} onChange={e=>setConForm({...conForm,unit_cost:e.target.value})}/></Field><div className="form-actions"><button disabled={busy} className="btn btn-primary">{busy?'Saving...':'Add consumable'}</button></div></form></Modal>
 <Modal open={!!adjust} onClose={()=>setAdjust(null)} title={`Adjust ${adjust?.name||''}`}><AdjustForm item={adjust} onDone={()=>{setAdjust(null);load()}}/></Modal>
 <Modal open={!!install} onClose={()=>setInstall(null)} title={`Assign ${install?.code||''}`}><InstallForm item={install} customers={customers} onDone={()=>{setInstall(null);load()}}/></Modal>
 </div>
}
function AdjustForm({item,onDone}){const[delta,setDelta]=useState(''),[reason,setReason]=useState('Stock adjustment'),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await adjustConsumable(item.id,Number(delta),reason);onDone()}catch(e){setError(e.message||'Could not adjust stock.')}finally{setBusy(false)}};return <form className="form-grid single" onSubmit={submit}>{error&&<div className="notice danger">{error}</div>}<Field label="Change quantity" hint="Use positive number to add stock, negative number when stock is used."><input required type="number" step="0.01" value={delta} onChange={e=>setDelta(e.target.value)} placeholder="e.g. 5 or -2"/></Field><Field label="Reason"><input value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="form-actions"><button disabled={busy} className="btn btn-primary">{busy?'Saving...':'Save adjustment'}</button></div></form>}
function InstallForm({item,customers,onDone}){const[customer,setCustomer]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async e=>{e.preventDefault();if(!canDirectInstallHairSystem(item)){setError('Only available hair systems can be installed directly. Reserved systems must be installed through the signed deal service.');return}setBusy(true);setError('');try{await installHairSystem(item.id,customer,null);onDone()}catch(e){setError(e.message||'Could not install hair system.')}finally{setBusy(false)}};return <form className="form-grid single" onSubmit={submit}>{error&&<div className="notice danger">{error}</div>}<Field label="Customer"><select required value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Select customer</option>{customers.map(c=><option value={c.id} key={c.id}>{customerLabel(c)}</option>)}</select></Field><div className="notice">This direct action is only for an available system. Reserved systems stay linked to their deal and are installed through the installation service.</div><div className="form-actions"><button disabled={busy} className="btn btn-primary">{busy?'Saving...':'Mark installed'}</button></div></form>}
