import React,{useEffect,useMemo,useState} from 'react'
import { Plus, Search, MessageCircle, UserCheck, Pencil, Trash2, AtSign } from 'lucide-react'
import { listLeads, saveLead, deleteLead, convertLead } from '../lib/api'
import { Badge, Empty, Field, Modal } from '../components/UI'
import { leadLabel, money, shortDate } from '../lib/utils'

const blank={whatsapp_name:'',name:'',phone:'',area:'',source:'Meta Ads',stage:'new',follow_up_date:'',potential_value:'',concern:'',notes:''}
const stageLabel=v=>({new:'New',contacted:'Contacted',interested:'Interested',consultation_booked:'Consultation booked',consultation_done:'Consultation done',deposit_paid:'Deposit paid',customer:'Customer',lost:'Lost'}[v]||v)

export default function Leads({goCustomer}){
  const [rows,setRows]=useState([]),[q,setQ]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false)
  const [convertOpen,setConvertOpen]=useState(false),[convertRow,setConvertRow]=useState(null),[customerName,setCustomerName]=useState('')
  const load=()=>listLeads().then(setRows)
  useEffect(()=>{load()},[])
  const filtered=useMemo(()=>rows.filter(x=>`${x.whatsapp_name||''} ${x.name||''} ${x.phone||''} ${x.area||''} ${x.source||''}`.toLowerCase().includes(q.toLowerCase())),[rows,q])
  const edit=x=>{setEditing(x.id);setForm({...blank,...x});setOpen(true)}
  const submit=async e=>{e.preventDefault();if(!form.whatsapp_name.trim()&&!form.name.trim()&&!form.phone.trim()){alert('Add at least a WhatsApp name, customer name, or phone number.');return}setBusy(true);try{await saveLead({...form,name:form.name.trim()||null,whatsapp_name:form.whatsapp_name.trim()||null,phone:form.phone.trim()||null,potential_value:Number(form.potential_value||0),follow_up_date:form.follow_up_date||null},editing);setOpen(false);setEditing(null);setForm(blank);await load()}finally{setBusy(false)}}
  const askConvert=x=>{setConvertRow(x);setCustomerName(x.name?.trim()||'');setConvertOpen(true)}
  const doConvert=async e=>{e.preventDefault();setBusy(true);try{const id=await convertLead(convertRow.id,customerName.trim()||null);setConvertOpen(false);setConvertRow(null);await load();goCustomer?.(id)}finally{setBusy(false)}}
  return <div className="page"><div className="page-head"><div><span className="eyebrow">CRM</span><h1>Leads</h1><p>Capture the enquiry first. Real name and phone can come later.</p></div><button className="btn btn-primary" onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}><Plus size={18}/>New lead</button></div>
    <div className="toolbar"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search WhatsApp name, name, phone, area..."/></div><span className="toolbar-count">{filtered.length} leads</span></div>
    <section className="panel table-panel">{filtered.length?<div className="responsive-table"><table><thead><tr><th>Lead</th><th>Stage</th><th>Source</th><th>Follow-up</th><th>Potential</th><th></th></tr></thead><tbody>{filtered.map(x=>{const overdue=x.follow_up_date&&x.follow_up_date<new Date().toLocaleDateString('en-CA')&&!['customer','lost'].includes(x.stage);return <tr key={x.id}><td data-label="Lead"><div className="lead-identity"><strong>{leadLabel(x)}</strong>{x.name&&x.whatsapp_name&&<span>{x.name}</span>}<span>{x.phone||'Phone not captured yet'}{x.area?` · ${x.area}`:''}</span></div></td><td data-label="Stage"><Badge tone={x.stage==='interested'?'success':x.stage==='lost'?'danger':x.stage==='customer'?'success':'neutral'}>{stageLabel(x.stage)}</Badge></td><td data-label="Source">{x.source}</td><td data-label="Follow-up"><span className={overdue?'text-danger':''}>{shortDate(x.follow_up_date)}</span></td><td data-label="Potential">{money(x.potential_value)}</td><td className="row-actions">{x.phone&&<a className="icon-btn" href={`https://wa.me/6${String(x.phone).replace(/\D/g,'').replace(/^6/,'')}`} target="_blank" rel="noreferrer" title="WhatsApp"><MessageCircle size={17}/></a>}<button className="icon-btn" onClick={()=>edit(x)} title="Edit"><Pencil size={17}/></button>{!['customer','lost'].includes(x.stage)&&<button className="icon-btn success" onClick={()=>askConvert(x)} title="Convert to customer"><UserCheck size={17}/></button>}<button className="icon-btn danger" onClick={async()=>{if(confirm('Delete this lead?')){await deleteLead(x.id);load()}}} title="Delete"><Trash2 size={17}/></button></td></tr>})}</tbody></table></div>:<Empty title="No leads yet" text="Start with whatever you know — even only a WhatsApp display name."/>}</section>
    <Modal open={open} onClose={()=>setOpen(false)} title={editing?'Edit lead':'New lead'} wide><form className="form-grid" onSubmit={submit}>
      <Field label="WhatsApp / display name" hint="Best first field when the person has not shared their real name yet."><div className="input-icon"><AtSign size={17}/><input autoFocus value={form.whatsapp_name||''} onChange={e=>setForm({...form,whatsapp_name:e.target.value})} placeholder="e.g. Jason Home, A Bi customer..."/></div></Field>
      <Field label="Real name (optional)"><input value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Fill later if unknown"/></Field>
      <Field label="Phone / WhatsApp number (optional)"><input inputMode="tel" value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Can be added later"/></Field>
      <Field label="Area"><input value={form.area||''} onChange={e=>setForm({...form,area:e.target.value})}/></Field>
      <Field label="Source"><select value={form.source} onChange={e=>setForm({...form,source:e.target.value})}>{['Meta Ads','TikTok','Instagram','Xiaohongshu','WhatsApp','Referral','Walk-in','Other'].map(v=><option key={v}>{v}</option>)}</select></Field>
      <Field label="Stage"><select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})}>{['new','contacted','interested','consultation_booked','consultation_done','deposit_paid','customer','lost'].map(v=><option key={v} value={v}>{stageLabel(v)}</option>)}</select></Field>
      <Field label="Follow-up date"><input type="date" value={form.follow_up_date||''} onChange={e=>setForm({...form,follow_up_date:e.target.value})}/></Field>
      <Field label="Potential value (RM)"><input type="number" min="0" value={form.potential_value} onChange={e=>setForm({...form,potential_value:e.target.value})}/></Field>
      <Field label="Hair concern"><input value={form.concern||''} onChange={e=>setForm({...form,concern:e.target.value})}/></Field>
      <Field label="Notes"><textarea value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></Field>
      <div className="form-actions"><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Cancel</button><button disabled={busy} className="btn btn-primary">{busy?'Saving...':'Save lead'}</button></div>
    </form></Modal>
    <Modal open={convertOpen} onClose={()=>setConvertOpen(false)} title="Convert to customer"><form className="form-grid single" onSubmit={doConvert}><div className="notice">This creates a customer profile with the information you already have. The WhatsApp display name stays as the visible identity until you learn the real name.</div><Field label="Real name (optional)"><input autoFocus value={customerName} onChange={e=>setCustomerName(e.target.value)} /></Field><div className="form-actions"><button type="button" className="btn btn-ghost" onClick={()=>setConvertOpen(false)}>Cancel</button><button disabled={busy} className="btn btn-primary">Create customer</button></div></form></Modal>
  </div>
}
