import React,{useEffect,useMemo,useState} from 'react'
import { Plus, Search, MessageCircle, UserCheck, Pencil, Trash2 } from 'lucide-react'
import { listLeads, saveLead, deleteLead, convertLead } from '../lib/api'
import { Badge, Empty, Field, Modal } from '../components/UI'
import { money, shortDate } from '../lib/utils'

const blank={name:'',phone:'',area:'',source:'Meta Ads',stage:'new',follow_up_date:'',potential_value:'',concern:'',notes:''}
export default function Leads({goCustomer}){
  const [rows,setRows]=useState([]),[q,setQ]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false)
  const load=()=>listLeads().then(setRows)
  useEffect(()=>{load()},[])
  const filtered=useMemo(()=>rows.filter(x=>`${x.name} ${x.phone} ${x.area} ${x.source}`.toLowerCase().includes(q.toLowerCase())),[rows,q])
  const edit=x=>{setEditing(x.id);setForm({...blank,...x});setOpen(true)}
  const submit=async e=>{e.preventDefault();setBusy(true);try{await saveLead({...form,potential_value:Number(form.potential_value||0),follow_up_date:form.follow_up_date||null},editing);setOpen(false);setEditing(null);setForm(blank);await load()}finally{setBusy(false)}}
  const convert=async x=>{if(!confirm(`Convert ${x.name} to customer?`))return; const id=await convertLead(x); await load(); goCustomer?.(id)}
  return <div className="page"><div className="page-head"><div><span className="eyebrow">CRM</span><h1>Leads</h1><p>Follow up quickly and turn enquiries into customers.</p></div><button className="btn btn-primary" onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}><Plus size={17}/>New lead</button></div>
    <div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, phone, area..."/></div><span className="toolbar-count">{filtered.length} leads</span></div>
    <section className="panel table-panel">{filtered.length?<div className="responsive-table"><table><thead><tr><th>Lead</th><th>Stage</th><th>Source</th><th>Follow-up</th><th>Potential</th><th></th></tr></thead><tbody>{filtered.map(x=>{const overdue=x.follow_up_date&&x.follow_up_date<new Date().toISOString().slice(0,10)&&!['customer','lost'].includes(x.stage);return <tr key={x.id}><td data-label="Lead"><strong>{x.name}</strong><span>{x.phone||'No phone'}{x.area?` · ${x.area}`:''}</span></td><td data-label="Stage"><Badge tone={x.stage==='interested'?'success':x.stage==='lost'?'danger':'neutral'}>{x.stage}</Badge></td><td data-label="Source">{x.source}</td><td data-label="Follow-up"><span className={overdue?'text-danger':''}>{shortDate(x.follow_up_date)}</span></td><td data-label="Potential">{money(x.potential_value)}</td><td className="row-actions"><a className="icon-btn" href={`https://wa.me/6${String(x.phone||'').replace(/\D/g,'').replace(/^6/,'')}`} target="_blank" rel="noreferrer"><MessageCircle size={17}/></a><button className="icon-btn" onClick={()=>edit(x)}><Pencil size={17}/></button>{!['customer','lost'].includes(x.stage)&&<button className="icon-btn success" onClick={()=>convert(x)} title="Convert"><UserCheck size={17}/></button>}<button className="icon-btn danger" onClick={async()=>{if(confirm('Delete this lead?')){await deleteLead(x.id);load()}}}><Trash2 size={17}/></button></td></tr>})}</tbody></table></div>:<Empty title="No leads yet" text="Add enquiries from Meta, TikTok, referral or walk-in."/>}</section>
    <Modal open={open} onClose={()=>setOpen(false)} title={editing?'Edit lead':'New lead'} wide><form className="form-grid" onSubmit={submit}><Field label="Name"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Phone / WhatsApp"><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Area"><input value={form.area} onChange={e=>setForm({...form,area:e.target.value})}/></Field><Field label="Source"><select value={form.source} onChange={e=>setForm({...form,source:e.target.value})}>{['Meta Ads','TikTok','Instagram','Xiaohongshu','Referral','Walk-in','Other'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Stage"><select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})}>{['new','contacted','interested','consultation_booked','consultation_done','deposit_paid','customer','lost'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></Field><Field label="Follow-up date"><input type="date" value={form.follow_up_date||''} onChange={e=>setForm({...form,follow_up_date:e.target.value})}/></Field><Field label="Potential value (RM)"><input type="number" value={form.potential_value} onChange={e=>setForm({...form,potential_value:e.target.value})}/></Field><Field label="Hair concern"><input value={form.concern} onChange={e=>setForm({...form,concern:e.target.value})}/></Field><Field label="Notes"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><div className="form-actions"><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Cancel</button><button disabled={busy} className="btn btn-primary">{busy?'Saving...':'Save lead'}</button></div></form></Modal>
  </div>
}
