import React,{useEffect,useMemo,useState} from 'react'
import { Camera, Plus, Search, Trash2, Images, Columns2 } from 'lucide-react'
import { listMedia, listCustomers, listServices, signedMedia, uploadMedia, deleteMedia } from '../lib/api'
import { Badge,Empty,Field,Modal,Tabs } from '../components/UI'
import { customerLabel, shortDate } from '../lib/utils'

export default function Media({prefill}){
 const [rows,setRows]=useState([]),[customers,setCustomers]=useState([]),[services,setServices]=useState([]),[urls,setUrls]=useState({}),[open,setOpen]=useState(false),[tab,setTab]=useState('gallery'),[q,setQ]=useState(''),[kind,setKind]=useState('all')
 const [form,setForm]=useState({customer_id:'',service_id:'',kind:'before',consent:'private',file:null}),[busy,setBusy]=useState(false),[lightbox,setLightbox]=useState(null)
 const load=async()=>{const[r,c,s]=await Promise.all([listMedia(),listCustomers(),listServices()]);setRows(r);setCustomers(c);setServices(s);const pairs=await Promise.all(r.map(async m=>[m.id,await signedMedia(m.storage_path).catch(()=>null)]));setUrls(Object.fromEntries(pairs))}
 useEffect(()=>{load()},[])
 useEffect(()=>{if(prefill?.customer_id){setForm({customer_id:prefill.customer_id,service_id:prefill.service_id||'',kind:prefill.kind||'before',consent:'private',file:null});setOpen(true)}},[prefill?.customer_id,prefill?.service_id])
 const filtered=useMemo(()=>rows.filter(m=>(kind==='all'||m.kind===kind)&&`${customerLabel(m.customers)} ${m.kind} ${m.consent}`.toLowerCase().includes(q.toLowerCase())),[rows,q,kind])
 const customerServices=services.filter(s=>s.customer_id===form.customer_id&&['in_progress','completed'].includes(s.status))
 const groups=useMemo(()=>{const map={};filtered.forEach(m=>{const key=m.service_id||`customer:${m.customer_id}`;(map[key] ||= {customer:m.customers,service:m.services,items:[]}).items.push(m)});return Object.values(map).filter(g=>g.items.some(x=>x.kind==='before')&&g.items.some(x=>x.kind==='after'))},[filtered])
 async function submit(e){e.preventDefault();if(!form.file||!form.customer_id)return;setBusy(true);try{await uploadMedia(form.file,form.customer_id,form.service_id||null,form.kind,form.consent);setOpen(false);setForm({customer_id:'',service_id:'',kind:'before',consent:'private',file:null});await load()}finally{setBusy(false)}}
 const preview=form.file?URL.createObjectURL(form.file):null
 return <div className="page"><div className="page-head"><div><span className="eyebrow">MEDIA</span><h1>Before / After</h1><p>Upload, compare and manage customer transformation photos.</p></div><button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={18}/>Upload photo</button></div>
 <div className="media-toolbar"><Tabs value={tab} onChange={setTab} items={[{value:'gallery',label:'Gallery'},{value:'compare',label:'Compare'}]}/><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customer..."/></div><select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All types</option><option value="before">Before</option><option value="process">Process</option><option value="after">After</option></select></div>
 {tab==='gallery'&&<section className="panel">{filtered.length?<div className="media-grid big">{filtered.map(m=><article className="media-card functional" key={m.id}>{urls[m.id]?<button className="media-image-button" onClick={()=>setLightbox(m)}><img src={urls[m.id]} alt={m.kind}/></button>:<div className="media-placeholder"/>}<div className="media-card-copy"><div><strong>{customerLabel(m.customers)}</strong><span>{shortDate(m.created_at)}</span></div><div className="inline-actions"><Badge>{m.kind}</Badge><Badge tone={m.consent==='private'?'neutral':'success'}>{m.consent.replace('_',' ')}</Badge><button className="icon-btn danger mini" title="Delete" onClick={async()=>{if(confirm('Delete this photo?')){await deleteMedia(m);load()}}}><Trash2 size={15}/></button></div></div></article>)}</div>:<Empty title="No photos yet" text="Upload before, process or after photos. On mobile you can take a photo directly."/>}</section>}
 {tab==='compare'&&<section className="panel">{groups.length?<div className="compare-grid">{groups.map((g,i)=>{const before=g.items.filter(x=>x.kind==='before').at(-1),after=g.items.filter(x=>x.kind==='after').at(-1);return <div className="compare-card" key={i}><div className="compare-head"><div><strong>{customerLabel(g.customer)}</strong><span>{g.service?.service_type||'Transformation'}</span></div><Columns2 size={18}/></div><div className="compare-images"><button onClick={()=>setLightbox(before)}>{urls[before.id]?<img src={urls[before.id]} alt="Before"/>:<div/>}<span>Before</span></button><button onClick={()=>setLightbox(after)}>{urls[after.id]?<img src={urls[after.id]} alt="After"/>:<div/>}<span>After</span></button></div></div>})}</div>:<Empty title="No before/after pairs yet" text="Link both a Before and After photo to the same service to see a comparison."/>}</section>}
 <Modal open={open} onClose={()=>setOpen(false)} title="Upload customer photo" wide><form className="form-grid" onSubmit={submit}>{preview&&<div className="upload-preview-wrap span-2"><img className="upload-preview" src={preview} alt="Preview"/></div>}<Field label="Customer"><select required value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value,service_id:''})}><option value="">Select customer</option>{customers.map(c=><option value={c.id} key={c.id}>{customerLabel(c)}</option>)}</select></Field><Field label="Related service"><select value={form.service_id} onChange={e=>setForm({...form,service_id:e.target.value})}><option value="">Not linked</option>{customerServices.map(s=><option key={s.id} value={s.id}>{s.service_type} · {s.status==='in_progress'?'In progress':shortDate(s.completed_at)}</option>)}</select></Field><Field label="Photo"><input required type="file" accept="image/*" capture="environment" onChange={e=>setForm({...form,file:e.target.files?.[0]||null})}/></Field><Field label="Type"><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="before">Before</option><option value="process">Process</option><option value="after">After</option></select></Field><Field label="Consent"><select value={form.consent} onChange={e=>setForm({...form,consent:e.target.value})}><option value="private">Private only</option><option value="public_blur">Public — blur face</option><option value="public">Public</option></select></Field><div className="form-actions"><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Cancel</button><button disabled={busy} className="btn btn-primary"><Camera size={16}/>{busy?'Uploading...':'Upload'}</button></div></form></Modal>
 <Modal open={!!lightbox} onClose={()=>setLightbox(null)} title={lightbox?`${customerLabel(lightbox.customers)} · ${lightbox.kind}`:'Photo'} wide>{lightbox&&urls[lightbox.id]&&<img className="lightbox-image" src={urls[lightbox.id]} alt={lightbox.kind}/>}</Modal>
 </div>
}
