import React,{useEffect,useMemo,useState} from 'react'
import { Search, Plus, CheckCircle2, Trash2 } from 'lucide-react'
import { listPayments,listCustomers,listDeals,createPayment,updatePayment,deletePayment } from '../lib/api'
import { Badge,Empty,Field,Modal,Stat,Tabs } from '../components/UI'
import { customerLabel,money,shortDate } from '../lib/utils'
import { accountOutstanding } from '../lib/finance'

export default function Payments(){
 const[rows,setRows]=useState([]),[customers,setCustomers]=useState([]),[deals,setDeals]=useState([]),[q,setQ]=useState(''),[open,setOpen]=useState(false),[tab,setTab]=useState('all'),[form,setForm]=useState({customer_id:'',deal_id:'',type:'sale',method:'DuitNow QR',status:'paid',amount:'',reference:'',notes:''}),[busy,setBusy]=useState(false),[rowBusy,setRowBusy]=useState(null),[error,setError]=useState('')
 const load=async()=>{try{const[r,c,d]=await Promise.all([listPayments(),listCustomers(),listDeals(500)]);setRows(r);setCustomers(c);setDeals(d)}catch(e){setError(e.message||'Could not load payments.')}};useEffect(()=>{load()},[])
 const customerDeals=deals.filter(d=>d.customer_id===form.customer_id&&d.status!=='cancelled')
 const selectedDeal=customerDeals.find(d=>d.id===form.deal_id)||null
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await createPayment({...form,amount:Number(form.amount),allocated_amount:form.deal_id?Number(form.amount):null,paid_at:form.status==='paid'?new Date().toISOString():null});setOpen(false);setForm({customer_id:'',deal_id:'',type:'sale',method:'DuitNow QR',status:'paid',amount:'',reference:'',notes:''});await load()}catch(e){setError(e.message||'Could not save payment.')}finally{setBusy(false)}}
 const markPaid=async row=>{setRowBusy(row.id);setError('');try{await updatePayment(row.id,{status:'paid',paid_at:new Date().toISOString()});await load()}catch(e){setError(e.message||'Could not update payment.')}finally{setRowBusy(null)}}
 const removePayment=async row=>{if(!confirm('Delete this test payment?'))return;setRowBusy(row.id);setError('');try{await deletePayment(row.id);await load()}catch(e){setError(e.message||'Could not delete payment.')}finally{setRowBusy(null)}}
 const filtered=useMemo(()=>rows.filter(x=>(tab==='all'||(tab==='refund'?x.type==='refund':x.status===tab))&&`${customerLabel(x.customers)} ${x.type} ${x.method} ${x.status} ${x.reference||''}`.toLowerCase().includes(q.toLowerCase())),[rows,q,tab])
 const paid=rows.filter(x=>x.status==='paid'&&x.type!=='refund').reduce((a,x)=>a+Number(x.amount||0),0);const due=accountOutstanding(deals,rows);const refunds=rows.filter(x=>x.type==='refund'&&['paid','refunded'].includes(x.status)).reduce((a,x)=>a+Number(x.amount||0),0)
 return <div className="page"><div className="page-head"><div><span className="eyebrow">MONEY</span><h1>Payments</h1><p>Keep paid, outstanding, deposits and refunds easy to read.</p></div><button className="btn btn-primary" onClick={()=>{setError('');setOpen(true)}}><Plus size={18}/>Add payment</button></div>
 {error&&<div className="notice danger">{error}</div>}
 <div className="stats-grid compact"><Stat label="Total paid" value={money(paid)}/><Stat label="Outstanding" value={money(due)} tone={due?'warn':'default'}/><Stat label="Refunds" value={money(refunds)}/><Stat label="Transactions" value={rows.length}/></div>
 <div className="payment-toolbar"><Tabs value={tab} onChange={setTab} items={[{value:'all',label:'All'},{value:'outstanding',label:'Outstanding'},{value:'paid',label:'Paid'},{value:'refund',label:'Refunds'}]}/><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customer, method, reference..."/></div></div>
 <section className="panel table-panel">{filtered.length?<div className="responsive-table"><table><thead><tr><th>Customer</th><th>Type</th><th>Order</th><th>Method</th><th>Status</th><th>Date</th><th>Amount</th><th></th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td data-label="Customer"><strong>{customerLabel(x.customers)}</strong></td><td data-label="Type">{x.type}</td><td data-label="Order">{x.payment_allocations?.[0]?`Linked · ${money(x.payment_allocations[0].deals?.balance_amount)}`:'—'}</td><td data-label="Method">{x.method}</td><td data-label="Status"><Badge tone={x.status==='paid'?'success':x.status==='outstanding'?'warn':'neutral'}>{x.status}</Badge></td><td data-label="Date">{shortDate(x.paid_at||x.created_at)}</td><td data-label="Amount"><strong>{money(x.amount)}</strong></td><td className="row-actions">{x.status==='outstanding'&&<button disabled={rowBusy===x.id} className="btn btn-ghost btn-sm" onClick={()=>markPaid(x)}><CheckCircle2 size={15}/>{rowBusy===x.id?'Saving...':'Mark paid'}</button>}<button disabled={rowBusy===x.id} className="icon-btn danger mini" title="Delete test payment" onClick={()=>removePayment(x)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>:<Empty title="No payments in this view"/>}</section>
 <Modal open={open} onClose={()=>setOpen(false)} title="Add payment"><form className="form-grid single" onSubmit={submit}>{error&&<div className="notice danger">{error}</div>}<Field label="Customer"><select required value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value,deal_id:''})}><option value="">Select</option>{customers.map(c=><option key={c.id} value={c.id}>{customerLabel(c)}</option>)}</select></Field><Field label="Order / Deal"><select value={form.deal_id} onChange={e=>setForm({...form,deal_id:e.target.value})}><option value="">No order allocation</option>{customerDeals.map(d=><option key={d.id} value={d.id}>{shortDate(d.signed_at)} · {money(d.final_price)} · balance {money(d.balance_amount)}</option>)}</select></Field>{selectedDeal&&<div className="notice span-2">This payment will be allocated to the selected order. Current order balance: <strong>{money(selectedDeal.balance_amount)}</strong>.</div>}<Field label="Amount (RM)"><input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="Type"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{['sale','deposit','balance','refund'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Method"><select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}>{['Cash','Bank Transfer','DuitNow QR','Card','Other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="paid">Paid</option><option value="outstanding">Outstanding</option><option value="refunded">Refunded</option></select></Field><Field label="Reference"><input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></Field><Field label="Notes"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><div className="form-actions"><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Cancel</button><button disabled={busy} className="btn btn-primary">{busy?'Saving...':'Save payment'}</button></div></form></Modal>
 </div>
}
