import React,{useEffect,useMemo,useState} from 'react'
import { CheckCircle2, Clock3, UserRound, CalendarPlus, Play, XCircle, RotateCcw, Ban, ChevronDown } from 'lucide-react'
import { completeConsultation, getCustomer, listConsultations, listDeals, listHairSystems, startConsultation, resetAppointmentWorkflow, findWorkflowConflict } from '../lib/api'
import { Badge, Empty, Field, Modal, Tabs } from '../components/UI'
import { customerLabel, dateTime, leadLabel, money, shortDate } from '../lib/utils'
import { dealPaidAmount, dealRefundedAmount } from '../lib/finance'

const blank={concern:'',coverage_area:'',colour_preference:'',density_preference:'',hairline_preference:'',lifestyle:'',budget:'',recommendation:'',notes:'',follow_up_date:'',lost_reason:'',real_name:'',system_source:'stock',hair_system_id:'',base:'',colour:'',size:'',density:'',length:'',hair_type:'Human Hair',quoted_price:'',discount:'0',final_price:'',deposit_amount:'',expected_ready_date:'',payment_method:'DuitNow QR',payment_status:'paid',deal_notes:''}
const tone=o=>o==='signed'?'success':o==='follow_up'?'warn':o==='not_signed'?'danger':'neutral'
const labelFor=x=>x.customers?customerLabel(x.customers):leadLabel(x.leads)

export default function Sales({prefill,onDone,onViewCustomer,onBookInstallation,onStartInstallation}){
 const[tab,setTab]=useState('consultations'),[consultations,setConsultations]=useState([]),[deals,setDeals]=useState([]),[systems,setSystems]=useState([]),[active,setActive]=useState(null),[form,setForm]=useState(blank),[outcome,setOutcome]=useState('follow_up'),[open,setOpen]=useState(false),[signedResult,setSignedResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[showConsultDetails,setShowConsultDetails]=useState(false),[showDealDetails,setShowDealDetails]=useState(false)
 const load=async()=>{const[c,d,h]=await Promise.all([listConsultations(),listDeals(),listHairSystems()]);setConsultations(c);setDeals(d);setSystems(h)}
 useEffect(()=>{load()},[])
 useEffect(()=>{if(prefill?.id){openFromAppointment(prefill)}},[prefill?.id])
 const available=useMemo(()=>systems.filter(x=>x.status==='available'),[systems])
 async function openFromAppointment(a){setBusy(true);setError('');try{if(a.status!=='in_progress'){const conflict=await findWorkflowConflict({leadId:a.lead_id||null,customerId:a.customer_id||null,serviceType:a.service_type,excludeAppointmentId:a.id});if(conflict)throw new Error(`This person already has an active consultation (${conflict.status}, ${dateTime(conflict.scheduled_at)}). Finish or cancel that consultation first.`)}const id=await startConsultation(a.id,a.assigned_user_id||null);let rows=await listConsultations();setConsultations(rows);const c=rows.find(x=>x.id===id);openSession(c||{id,appointment_id:a.id,lead_id:a.lead_id,customer_id:a.customer_id,leads:a.leads,customers:a.customers});onDone?.()}catch(e){setError(e.message)}finally{setBusy(false)}}
 function openSession(c){setActive(c);setOutcome('follow_up');setShowConsultDetails(false);setShowDealDetails(false);setForm({...blank,concern:c.concern||'',coverage_area:c.coverage_area||'',colour_preference:c.colour_preference||'',density_preference:c.density_preference||'',hairline_preference:c.hairline_preference||'',lifestyle:c.lifestyle||'',budget:c.budget||'',recommendation:c.recommendation||'',notes:c.notes||'',follow_up_date:c.follow_up_date||'',lost_reason:c.lost_reason||'',real_name:c.customers?.name||c.leads?.name||''});setOpen(true);setError('')}
 async function finish(e){e.preventDefault();setBusy(true);setError('');try{const finalPrice=Number(form.final_price||Math.max(0,Number(form.quoted_price||0)-Number(form.discount||0)));const result=await completeConsultation(active.id,outcome,{...form,final_price:finalPrice});setOpen(false);setActive(null);await load();if(outcome==='signed'&&result?.customer_id){const detail=await getCustomer(result.customer_id);setSignedResult({customer:detail.customer,deal_id:result.deal_id})}}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function changeActiveStatus(target){if(!active?.appointment_id)return;const text=target==='confirmed'?'return this consultation to Booked':'cancel this consultation';if(!confirm(`Are you sure you want to ${text}?`))return;setBusy(true);setError('');try{await resetAppointmentWorkflow(active.appointment_id,target);setOpen(false);setActive(null);await load();onDone?.()}catch(e){setError(e.message||'Could not change consultation status.')}finally{setBusy(false)}}
 const inProgress=consultations.filter(x=>x.status==='in_progress')
 const done=consultations.filter(x=>x.status==='completed')
 return <div className="page sales-page">
  <div className="page-head"><div><span className="eyebrow">SALES WORKFLOW</span><h1>Consultations & Deals</h1><p>Consult first. Record the outcome. A client only exists after the deal is signed.</p></div></div>
  <Tabs value={tab} onChange={setTab} items={[{value:'consultations',label:`Consultations${inProgress.length?` (${inProgress.length} active)`:''}`},{value:'deals',label:`Signed deals (${deals.length})`}]}/>
  {error&&<div className="notice danger">{error}</div>}
  {tab==='consultations'&&<div className="sales-stack">
    {inProgress.length>0&&<section className="panel"><div className="section-head"><div><span className="eyebrow">IN PROGRESS</span><h2>Finish the consultation outcome</h2></div></div><div className="job-list">{inProgress.map(c=><button key={c.id} onClick={()=>openSession(c)}><span className="live-dot"/><div className="grow"><strong>{labelFor(c)}</strong><span>{c.appointments?dateTime(c.appointments.scheduled_at):'Consultation'} · {c.profiles?.full_name||'Unassigned'}</span></div><Badge tone="warn">in progress</Badge></button>)}</div></section>}
    <section className="panel"><div className="section-head"><div><span className="eyebrow">OUTCOMES</span><h2>Consultation history</h2></div></div>{done.length?<div className="consultation-list">{done.map(c=><div className="consultation-history-row" key={c.id}><div className="grow"><strong>{labelFor(c)}</strong><span>{c.appointments?dateTime(c.appointments.scheduled_at):shortDate(c.completed_at)} · {c.profiles?.full_name||'Admin'}</span></div><Badge tone={tone(c.outcome)}>{c.outcome?.replace('_',' ')||'completed'}</Badge></div>)}</div>:<Empty title="No completed consultations yet" text="Book a consultation from Leads or Calendar. After the visit, choose Signed, Follow up, or Not signed."/>}</section>
  </div>}
  {tab==='deals'&&<section className="panel"><div className="section-head"><div><span className="eyebrow">SIGNED CLIENTS</span><h2>Hair system deals</h2></div></div>{deals.length?<div className="deal-grid">{deals.map(d=><article className="deal-card" key={d.id}><div className="deal-head"><div><strong>{customerLabel(d.customers)}</strong><span>{shortDate(d.signed_at)}</span></div><Badge tone={d.status==='installed'?'success':d.status==='cancelled'?'danger':'neutral'}>{d.status.replaceAll('_',' ')}</Badge></div><div className="deal-specs"><span>Source<strong>{d.system_source}</strong></span><span>System<strong>{d.hair_systems?.code||d.base||'TBC'}</strong></span><span>Final<strong>{money(d.final_price)}</strong></span><span>Deposit target<strong>{money(d.deposit_amount)}</strong></span><span>Paid<strong>{money(dealPaidAmount(d))}</strong></span><span>Refunded<strong>{money(dealRefundedAmount(d))}</strong></span><span>Balance<strong>{money(d.balance_amount)}</strong></span></div><div className="deal-actions"><button className="btn btn-ghost btn-sm" onClick={()=>onViewCustomer?.(d.customer_id)}><UserRound size={15}/>Client</button>{!['installed','cancelled'].includes(d.status)&&<button className="btn btn-primary btn-sm" onClick={()=>onBookInstallation?.(d.customers)}><CalendarPlus size={15}/>Book installation</button>}</div></article>)}</div>:<Empty title="No signed deals yet" text="Signed consultation outcomes will appear here."/>}</section>}

  <Modal open={open} onClose={()=>setOpen(false)} title="Consultation outcome" wide>{active&&<form className="form-grid consultation-form" onSubmit={finish}>
    {error&&<div className="notice danger span-2">{error}</div>}
    <div className="consultation-person span-2"><div><span className="eyebrow">CONSULTATION</span><h3>{labelFor(active)}</h3><p>{active.appointments?dateTime(active.appointments.scheduled_at):'In progress'}</p></div><Badge tone="warn">in progress</Badge></div>
    <Field label="Hair concern"><input value={form.concern} onChange={e=>setForm({...form,concern:e.target.value})} placeholder="Top / crown / frontal..."/></Field><Field label="Coverage area"><input value={form.coverage_area} onChange={e=>setForm({...form,coverage_area:e.target.value})} placeholder="Top / crown / frontal..."/></Field>
    <Field label="Budget (RM)"><input type="number" min="0" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/></Field><Field label="Recommendation"><textarea value={form.recommendation} onChange={e=>setForm({...form,recommendation:e.target.value})} placeholder="Main recommendation / important note"/></Field>
    <div className="span-2 optional-section"><button type="button" className="optional-toggle" onClick={()=>setShowConsultDetails(!showConsultDetails)}><span>{showConsultDetails?'Hide':'More'} consultation details</span><ChevronDown size={16} className={showConsultDetails?'open':''}/></button>{showConsultDetails&&<div className="optional-grid"><Field label="Colour preference"><input value={form.colour_preference} onChange={e=>setForm({...form,colour_preference:e.target.value})}/></Field><Field label="Density preference"><input value={form.density_preference} onChange={e=>setForm({...form,density_preference:e.target.value})}/></Field><Field label="Hairline preference"><input value={form.hairline_preference} onChange={e=>setForm({...form,hairline_preference:e.target.value})}/></Field><Field label="Lifestyle"><textarea value={form.lifestyle} onChange={e=>setForm({...form,lifestyle:e.target.value})}/></Field></div>}</div>
    <div className="span-2 outcome-picker"><span className="field-label">Consultation outcome</span><div><button type="button" className={outcome==='signed'?'active success':''} onClick={()=>setOutcome('signed')}><CheckCircle2 size={18}/>Signed</button><button type="button" className={outcome==='follow_up'?'active warn':''} onClick={()=>setOutcome('follow_up')}><Clock3 size={18}/>Follow up</button><button type="button" className={outcome==='not_signed'?'active danger':''} onClick={()=>setOutcome('not_signed')}><XCircle size={18}/>Not signed</button></div></div>
    {outcome==='follow_up'&&<><Field label="Follow-up date"><input required type="date" value={form.follow_up_date} onChange={e=>setForm({...form,follow_up_date:e.target.value})}/></Field><Field label="Follow-up notes"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Price / discuss with family / compare..."/></Field></>}
    {outcome==='not_signed'&&<><Field label="Reason"><select value={form.lost_reason} onChange={e=>setForm({...form,lost_reason:e.target.value})}><option value="">Select reason</option>{['Price','Not ready','Competitor','Distance','Not suitable','No reply','Other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Notes"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></>}
    {outcome==='signed'&&<>
      <div className="span-2 signed-section-title"><span className="eyebrow">SIGNED DEAL</span><h3>Hair system selection & money</h3></div>
      <Field label="Real name (if known)"><input value={form.real_name} onChange={e=>setForm({...form,real_name:e.target.value})}/></Field><Field label="System source"><select value={form.system_source} onChange={e=>setForm({...form,system_source:e.target.value,hair_system_id:e.target.value==='stock'?form.hair_system_id:''})}><option value="stock">Ready stock</option><option value="custom">Custom order</option><option value="undecided">Decide later</option></select></Field>
      {form.system_source==='stock'&&<Field label="Reserve ready stock"><select value={form.hair_system_id} onChange={e=>{const h=available.find(x=>x.id===e.target.value);setForm({...form,hair_system_id:e.target.value,base:h?.base||form.base,colour:h?.colour||form.colour,size:h?.size||form.size,density:h?.density||form.density,length:h?.length||form.length,hair_type:h?.hair_type||form.hair_type})}}><option value="">Choose later</option>{available.map(h=><option key={h.id} value={h.id}>{h.code} · {h.base||'—'} · {h.colour||'—'} · {h.size||'—'}</option>)}</select></Field>}
      {form.system_source==='custom'&&<Field label="Expected ready date"><input type="date" value={form.expected_ready_date} onChange={e=>setForm({...form,expected_ready_date:e.target.value})}/></Field>}
      <div className="span-2 optional-section"><button type="button" className="optional-toggle" onClick={()=>setShowDealDetails(!showDealDetails)}><span>{showDealDetails?'Hide':'More'} system / pricing details</span><ChevronDown size={16} className={showDealDetails?'open':''}/></button>{showDealDetails&&<div className="optional-grid"><Field label="Base"><input value={form.base} onChange={e=>setForm({...form,base:e.target.value})}/></Field><Field label="Colour"><input value={form.colour} onChange={e=>setForm({...form,colour:e.target.value})}/></Field><Field label="Size"><input value={form.size} onChange={e=>setForm({...form,size:e.target.value})}/></Field><Field label="Density"><input value={form.density} onChange={e=>setForm({...form,density:e.target.value})}/></Field><Field label="Length"><input value={form.length} onChange={e=>setForm({...form,length:e.target.value})}/></Field><Field label="Hair type"><input value={form.hair_type} onChange={e=>setForm({...form,hair_type:e.target.value})}/></Field><Field label="Quoted price (RM)"><input type="number" min="0" step="0.01" value={form.quoted_price} onChange={e=>setForm({...form,quoted_price:e.target.value,final_price:String(Math.max(0,Number(e.target.value||0)-Number(form.discount||0)))})}/></Field><Field label="Discount (RM)"><input type="number" min="0" step="0.01" value={form.discount} onChange={e=>setForm({...form,discount:e.target.value,final_price:String(Math.max(0,Number(form.quoted_price||0)-Number(e.target.value||0)))})}/></Field></div>}</div>
      <Field label="Final price (RM)"><input type="number" min="0" step="0.01" value={form.final_price} onChange={e=>setForm({...form,final_price:e.target.value})}/></Field><Field label="Deposit (RM)"><input type="number" min="0" step="0.01" value={form.deposit_amount} onChange={e=>setForm({...form,deposit_amount:e.target.value})}/></Field>
      <Field label="Deposit payment"><div className="dual-input"><select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}>{['Cash','Bank Transfer','DuitNow QR','Card','Other'].map(x=><option key={x}>{x}</option>)}</select><select value={form.payment_status} onChange={e=>setForm({...form,payment_status:e.target.value})}><option value="paid">Paid</option><option value="outstanding">Outstanding</option></select></div></Field><Field label="Deal notes"><textarea value={form.deal_notes} onChange={e=>setForm({...form,deal_notes:e.target.value})}/></Field>
    </>}
    <div className="form-actions consultation-actions"><button type="button" className="btn btn-ghost" disabled={busy} onClick={()=>changeActiveStatus('confirmed')}><RotateCcw size={16}/>Return to booked</button><button type="button" className="btn btn-danger-ghost" disabled={busy} onClick={()=>changeActiveStatus('cancelled')}><Ban size={16}/>Cancel consultation</button><span className="grow"/><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Keep open</button><button disabled={busy} className="btn btn-primary">{busy?'Saving...':outcome==='signed'?'Save signed deal':outcome==='follow_up'?'Save follow-up':'Close as not signed'}</button></div>
  </form>}</Modal>
  <Modal open={!!signedResult} onClose={()=>setSignedResult(null)} title="Deal signed">{signedResult&&<div className="completion-card"><div className="completion-check"><CheckCircle2 size={28}/></div><h3>Deal signed</h3><p>Most clients continue with installation on the same day. Choose what happens next.</p><div className="completion-actions"><button className="btn btn-ghost" onClick={()=>{const c=signedResult.customer;setSignedResult(null);onViewCustomer?.(c.id)}}><UserRound size={16}/>View client</button><button className="btn btn-ghost" onClick={()=>{const c=signedResult.customer;setSignedResult(null);onBookInstallation?.(c)}}><CalendarPlus size={16}/>Book later</button><button className="btn btn-primary" onClick={()=>{const c=signedResult.customer;setSignedResult(null);onStartInstallation?.(c)}}><Play size={16}/>Start installation now</button></div></div>}</Modal>
 </div>
}
