import React,{useEffect,useMemo,useState} from 'react'
import { Plus, Search, Scissors } from 'lucide-react'
import { listCustomers,listProfiles,listConsumables,createService } from '../lib/api'
import { Empty, Field, Modal } from '../components/UI'
import { money, shortDate } from '../lib/utils'

const serviceTypes=['New System Installation','Maintenance','Cleaning + Rebond','Haircut / Adjustment','Hairline Touch-up','Consultation','Other']
export default function Services({prefillCustomer,onDone}){
 const [customers,setCustomers]=useState([]),[profiles,setProfiles]=useState([]),[cons,setCons]=useState([]),[open,setOpen]=useState(false),[q,setQ]=useState('')
 const [form,setForm]=useState({customer_id:'',service_type:'Maintenance',technician_id:'',amount:'',next_maintenance_date:'',technical_notes:'',customer_notes:'',payment_method:'DuitNow QR',payment_status:'paid'}),[used,setUsed]=useState([]),[busy,setBusy]=useState(false)
 const load=async()=>{const[c,p,co]=await Promise.all([listCustomers(),listProfiles(),listConsumables()]);setCustomers(c);setProfiles(p);setCons(co)};useEffect(()=>{load()},[])
 useEffect(()=>{if(prefillCustomer){setForm(f=>({...f,customer_id:prefillCustomer.id}));setOpen(true)}},[prefillCustomer?.id])
 const filtered=useMemo(()=>customers.filter(c=>`${c.name} ${c.phone} ${c.area}`.toLowerCase().includes(q.toLowerCase())),[customers,q])
 const addUse=()=>setUsed([...used,{consumable_id:'',qty:1}])
 const submit=async e=>{e.preventDefault();setBusy(true);try{await createService({...form,amount:Number(form.amount||0),next_maintenance_date:form.next_maintenance_date||null,completed_at:new Date().toISOString()},used.filter(x=>x.consumable_id&&Number(x.qty)>0).map(x=>({...x,qty:Number(x.qty)})));setOpen(false);setUsed([]);setForm({customer_id:'',service_type:'Maintenance',technician_id:'',amount:'',next_maintenance_date:'',technical_notes:'',customer_notes:'',payment_method:'DuitNow QR',payment_status:'paid'});onDone?.()}finally{setBusy(false)}}
 return <div className="page"><div className="page-head"><div><span className="eyebrow">SERVICE FLOW</span><h1>Service</h1><p>Complete the visit, deduct consumables, collect payment and set next maintenance.</p></div><button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={17}/>Complete service</button></div>
 <div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find customer to start service..."/></div></div>
 <section className="panel"><div className="section-head"><div><span className="eyebrow">CUSTOMERS</span><h2>Start from a customer</h2></div></div>{filtered.length?<div className="service-customer-grid">{filtered.slice(0,50).map(c=><button key={c.id} onClick={()=>{setForm({...form,customer_id:c.id});setOpen(true)}}><div className="avatar large">{c.name?.[0]}</div><div className="grow"><strong>{c.name}</strong><span>{c.phone||'No phone'} · {c.area||'No area'}</span></div><Scissors size={18}/></button>)}</div>:<Empty title="No customers found"/>}</section>
 <Modal open={open} onClose={()=>setOpen(false)} title="Complete service" wide><form className="form-grid" onSubmit={submit}><Field label="Customer"><select required value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Service"><select value={form.service_type} onChange={e=>setForm({...form,service_type:e.target.value})}>{serviceTypes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Technician"><select required value={form.technician_id} onChange={e=>setForm({...form,technician_id:e.target.value})}><option value="">Select Yong / Ah Bi</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></Field><Field label="Amount (RM)"><input type="number" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="Next maintenance"><input type="date" value={form.next_maintenance_date} onChange={e=>setForm({...form,next_maintenance_date:e.target.value})}/></Field><Field label="Payment method"><select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}>{['Cash','Bank Transfer','DuitNow QR','Card','Other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Payment status"><select value={form.payment_status} onChange={e=>setForm({...form,payment_status:e.target.value})}><option value="paid">Paid</option><option value="outstanding">Outstanding</option></select></Field><Field label="Technical notes"><textarea value={form.technical_notes} onChange={e=>setForm({...form,technical_notes:e.target.value})}/></Field><Field label="Customer notes"><textarea value={form.customer_notes} onChange={e=>setForm({...form,customer_notes:e.target.value})}/></Field><div className="span-2 consumable-use"><div className="section-head mini"><div><span className="field-label">Consumables used</span></div><button type="button" className="btn btn-ghost btn-sm" onClick={addUse}>+ Add item</button></div>{used.map((u,i)=><div className="consume-row" key={i}><select value={u.consumable_id} onChange={e=>setUsed(used.map((x,j)=>j===i?{...x,consumable_id:e.target.value}:x))}><option value="">Select consumable</option>{cons.map(c=><option key={c.id} value={c.id}>{c.name} · {c.qty} {c.unit}</option>)}</select><input type="number" min="0.01" step="0.01" value={u.qty} onChange={e=>setUsed(used.map((x,j)=>j===i?{...x,qty:e.target.value}:x))}/><button type="button" className="icon-btn danger" onClick={()=>setUsed(used.filter((_,j)=>j!==i))}>×</button></div>)}</div><div className="form-actions"><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Cancel</button><button disabled={busy} className="btn btn-primary">{busy?'Completing...':'Complete service'}</button></div></form></Modal>
 </div>
}
